# AMZ-Driverless
# Copyright (c) 2018 Authors:
#   - Juraj Kabzan <kabzanj@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

car:

  inertia:
    m:        195.0   #190.0   # Weight of the Vehicle [kg]
    m_driver: 0.0              # Weight of the driver  [kg]
    g:        9.81             # Graviti force         [m/s^2]
    I_z:      95.0    #110     # Inertial force I_zz 

  kinematics:
    l: 1.56           #evtl auch 1.54 #1.53   # Vehicle Length [m]
    b_F: 1.22 #0.858        #1.22                   # From COG to front axle [m]
    b_R: 1.22 #0.702        #1.22                   # From COG to rear axle [m]
    w_front: 0.45     #0.5                    # Percentage of weight front
    h_cg: 0.27        #0.262                  # Heights of COG [m]

    # l_F = l * (1 - w_front);  # Front cg lever arm [m]
    # l_R = l * w_front;  # Rear  cg lever arm [m]

  # Magic Formula:
  # y=D*sin(C*atan(B*(1-E)*x+E*atan(B*x)))
  tire:
    tire_coefficient: 1.0 #1.0 
    lateral: 
      D1: 3.1352
      D2: 0.7293
      B: -0.1669
      C: -1.4801
      #B: 12.56
      #C: -1.38
      #D: 1.60
      #E: -0.58
    longitudinal:
      D1: 3.1352
      D2: 0.7293
      B: -0.1669
      C: -1.4801
      #B: 12.56
      #C: -1.38
      #D: 1.60
      #E: -0.58


  aero:
    C_Down: # F_Downforce = C_Downforce*v_x^2; C_Downforce = a*b*c
      #a: 0
      #b: 0
      #c: 0 
      a: 1.22   #wahrscheinlich Luftdichte (ca. 1.225 auf Meereshöhe)
      b: 4.0    #Wert von Niebling #2.6    #Luftwiderstandsbeiwert (Drag Coefficient)
      c: 0.5    #0.6    #Stirnfläche des Fahrzeugs
    C_drag: # F_Drag = C_Drag*v_x^2; C_drag = a*b*c
      #a: 0
      #b: 0
      #c: 0 
      a: 1.22   #0.7 #wahrscheinlich Luftdichte (ca. 1.225 auf Meereshöhe)
      b: 1.1    #Wert von Niebling #1.4 von Nils #1.0
      c: 0.5    #1.0

  drivetrain:
    Cm1: 2000 #5000 #<-- evtl ein Fehler #4475   #5000/4 dann pro Rad    #max kraft von bremse #2200 4475
    Cm_brake: 5000 #3000
    Cr0: 180 #19 #180     #rolling resistance
    inertia: 0.4 #0.4 # wheel_plus_packaging - was zur hölle ist das?! Anscheinend Trägheitsmoment/ anscheinend alles was am Rad dran ist wird gewogen/ also alles was sich dreht, Felge, Reifen, Tripode ...
    r_dyn: 0.195 #0.231 #dynamischer Radius des Rades
    nm_wheels: 2 #4 # Stressig #man sollte auf 2 gehen
    
  torque_vectoring: #schauen wir mal - haben wir nicht
    K_FFW: 0.0        #2.1
    K_p: 0.0          #500 
    shrinkage: 0.0    #0.8
    K_stability: 0.0  #0.004
